server:
  port: 8083

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dan-Elioth/microservicios.git
          searchPaths: config-data
          username: Dan-Elioth
          password: 108110
          default-label: main


  security:
    user:
      name: root
      password: s3cr3t


